name: Build and deploy Python app to Azure Web App - AjiraBora

on:
  push:
    branches:
      - nyams
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4  # Updated to v4 for better support
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r backend/jobportal/requirements.txt

      # Optional: Add a step here to run tests if needed, e.g., using PyTest or Django's test suite

      - name: Zip project for deployment
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" "*.github/*"  # Exclude unnecessary directories

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'AjiraBora'  # Ensure this matches your Azure Web App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_99355A04F4784756A334F384C5327A5E }}
